Repository kugods-HabitTama/dahae-server, pull requests merged in 2022-12, with the labels that each got.

#12 [Feat] 회원가입, 로그인 관련 api 개발
  package-lock.json
  package.json
  prisma/migrations/20221128053530_add_refresh_token/migration.sql
  prisma/migrations/20221203042936_/migration.sql
  prisma/schema.prisma
  src/app/app.module.ts
  src/app/modules/config.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/create.user.dto.ts
  src/auth/payload/create.user.payload.ts
  src/auth/payload/login.user.payload.ts
  src/auth/type/token.response.type.ts
  src/user/user.repository.ts
  yarn.lock
Labels: feature

#14 [Schema] Minor Patch
  prisma/migrations/20221205134813_minor_patch/migration.sql
  prisma/schema.prisma
Labels: DB migration

#24 [Infra] development 배포 파이프라인 구축
  .github/workflows/dev.yml
  dev.dockerfile
  package.json
Labels: Infra/Deploy

#25 [Test] Deploy
  src/app/app.service.ts
Labels: Infra/Deploy

#26 [Infra] beanstalk에 바로 배포하도록 dev workflow 수정
  .github/workflows/dev.yml
  Dockerrun.aws.json
  src/app/app.service.ts
Labels: Infra/Deploy

#28 [Infra] logger 세팅
  src/app/app.module.ts
  src/common/middlewares/logger.middleware.ts
Labels: Infra/Deploy

#22 [Feat] CurrentUser Decorator 추가
  src/auth/decorator/user.decorator.ts
  src/user/user.controller.ts
Labels: feature

#20 [Feat] Habit 생성하는 API
  src/app/app.module.ts
  src/common/validators/isAfterConstraint.ts
  src/habit/const/habitRecordDay.const.ts
  src/habit/habit.controller.spec.ts
  src/habit/habit.controller.ts
  src/habit/habit.module.ts
  src/habit/habit.repository.ts
  src/habit/habit.service.spec.ts
  src/habit/habit.service.ts
  src/habit/payload/create.habit.payload.ts
  src/utils/date.ts
Labels: feature

#31 [Infra/Fix] 배포 시 도커 이미지 버전 명시
  dev.dockerfile
Labels: fix, Infra/Deploy

#36 [Refactor] Dto 변경 및 Swagger 개선
  src/habit/dto/get.habit.list.dto.ts
  src/habit/dto/get.habit.record.dto.ts
  src/habit/dto/get.habit.record.list.dto.ts
  src/habit/dto/habit.dto.ts
  src/habit/dto/habit.record.dto.ts
  src/habit/habit.controller.ts
  src/habit/habit.service.ts
  src/habit/payload/change.progress.payload.ts
  src/habit/payload/create.habit.payload.ts
  src/habit/payload/update.habit.payload.ts
  src/habit/query/date.query.ts
Labels: feature

#40 [Infra] CI workflow 추가
  .github/workflows/CI.yml
  dev.dockerfile
  package-lock.json
  yarn.lock
Labels: Infra/Deploy

#38 [Refactor] habit 모듈에서 prisma 의존성 제거
  src/habit/dto/habit.dto.ts
  src/habit/dto/habit.record.dto.ts
  src/habit/habit.repository.ts
  src/habit/habit.service.ts
  src/habit/type/habit.data.type.ts
  src/habit/type/habit.with.records.type.ts
Labels: feature

#46 [Schema] habit.time type 변경
  prisma/migrations/20221223070747_change_habit_type_datetime_to_string/migration.sql
  prisma/migrations/20221223072920_add_not_null_to_habit_time/migration.sql
  prisma/schema.prisma
  prisma/scripts/habit-time-script.ts
  src/habit/habit.repository.ts
  src/habit/habit.service.ts
  src/utils/date.ts
Labels: DB migration
